[workspace]
authors = ["Zimmerman Group, Andreas Copan (pixi environment)"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]
requires-pixi = ">=0.60.0"
preview = ["pixi-build"]

[package]
name = "gsm"
version = "0.1.0"

[package.build.backend]
name = "pixi-build-cmake"
version = ">=0.3.6,<=0.3.8"

[tasks]
# gsm <N> -> initial000N.xyz
test = { cmd = "gsm 1", cwd = "TEST/dielsAlder/mopac/de-gsm" }

[package.build-dependencies]
cmake = "*"

[package.host-dependencies]

[package.target.linux-64.host-dependencies]
libstdcxx-ng = "*"
mkl = "*"
mkl-include = "*"

[package.target.osx-arm64.host-dependencies]
openblas = "*"

[dependencies]
mopac = "*"
gsm = {path = "."}
