[workspace]
authors = ["Zimmerman Group, Andreas Copan (pixi environment)"]
channels = ["conda-forge"]
platforms = ["linux-64"]
# requires-pixi = ">=0.50.2"
preview = ["pixi-build"]

[package]
name = "gsm"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "==0.1.11" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[tasks]
# gsm <N> -> initial000N.xyz
test = { cmd = "gsm 1", cwd = "TEST/dielsAlder/mopac/de-gsm" }

[package.build-dependencies]
cmake = "*"

[package.host-dependencies]
libstdcxx-ng = "*"
mkl = "*"
mkl-include = "*"

[dependencies]
mkl = "*"
mopac = "*"
gsm = {path = "."}
